# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SFRPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('hhmodel_version', models.SlugField(max_length=100)),
                ('cost_estimate', models.FloatField()),
                ('flood_eliminated_parcels', models.FloatField()),
                ('flood_improved_parcels', models.FloatField()),
                ('flood_increased_parcels', models.FloatField()),
                ('flood_new_parcels', models.FloatField()),
            ],
        ),
    ]
