# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfrphase',
            name='data_directory',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
