# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0002_sfrphase_data_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('data_directory', models.CharField(default='', max_length=100, unique=True)),
                ('data_file', models.CharField(default='', max_length=100, unique=True)),
                ('cost_estimate', models.FloatField()),
                ('parcel_hours_reduced', models.FloatField()),
                ('parcel_hours_increased', models.FloatField()),
                ('parcel_hours_new', models.FloatField()),
                ('sewer_miles_new', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
