# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0003_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'default': 0}),
            preserve_default=False,
        ),
    ]
