# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0004_phase_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='json_data',
        ),
        migrations.AddField(
            model_name='phase',
            name='delta_parcels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='phase',
            name='new_conduits',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='phase',
            name='parcels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
