# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0005_auto_20170218_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='delta_parcels',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='parcels',
        ),
    ]
